# Generated by Django 5.2.4 on 2025-08-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empname', models.CharField(max_length=64)),
                ('Empid', models.IntegerField()),
                ('Empcity', models.CharField(max_length=64)),
            ],
        ),
    ]
