# Generated by Django 5.2.4 on 2025-09-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empid', models.IntegerField()),
                ('Name', models.CharField(max_length=64)),
                ('Designation', models.CharField(max_length=64)),
                ('City', models.CharField(max_length=64)),
            ],
        ),
    ]
