# Generated by Django 5.2.4 on 2025-09-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRMPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customername', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Company', models.CharField(max_length=200)),
                ('Contactnumber', models.IntegerField()),
                ('Status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost')], max_length=20)),
                ('Sources', models.CharField(choices=[('web', 'Website'), ('email', 'Email'), ('phone', 'Phone'), ('referral', 'Referral'), ('ads', 'Ads'), ('other', 'Other')], max_length=20)),
            ],
        ),
    ]
