# Generated by Django 5.2.4 on 2025-08-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=64)),
                ('employee_id', models.IntegerField()),
                ('employee_designation', models.CharField(max_length=64)),
            ],
        ),
    ]
