# Generated by Django 5.2.4 on 2025-08-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticketsdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employeename', models.CharField(max_length=64)),
                ('Summary', models.CharField(max_length=64)),
                ('Description', models.CharField(max_length=64)),
                ('Priority', models.IntegerField()),
            ],
        ),
    ]
