# Generated by Django 5.2.4 on 2025-08-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSupport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsdata',
            name='Status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=64),
        ),
    ]
