# Generated by Django 5.2.4 on 2025-08-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSupport', '0002_ticketsdata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsdata',
            name='Description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketsdata',
            name='Priority',
            field=models.CharField(choices=[('Priority 1', 'Top Priority'), ('Priority 2', 'Priority'), ('Priority 3', 'Low')], default='Priority 3'),
        ),
    ]
