# Generated by Django 5.2.4 on 2025-08-30 14:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSupport', '0003_alter_ticketsdata_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsdata',
            name='Ticketnumber',
            field=models.UUIDField(default=None, editable=False, unique=True,null=True, blank=True),
        ),
    ]
