# Generated by Django 5.2.4 on 2025-09-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSupport', '0004_ticketsdata_ticketnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsdata',
            name='Ticketnumber',
        ),
        migrations.AlterField(
            model_name='ticketsdata',
            name='Priority',
            field=models.CharField(choices=[('Top Priority', 'Top Priority'), ('Priority', 'Priority'), ('Low', 'Low')], default='Low'),
        ),
    ]
