# Generated by Django 5.2.4 on 2025-09-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITSupport', '0005_remove_ticketsdata_ticketnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsdata',
            name='Priority',
            field=models.CharField(choices=[('Priority 1', 'Top Priority'), ('Priority 2', 'Priority'), ('Priority 3', 'Low')], default='Priority 3'),
        ),
    ]
